### ISSUE TITLE
Set default value for `options` of `Mastodon.generateAuthUrl`

### ISSUE THREAD

**Issue by aji-su** [onsen-ui/mstdn#1]
Could you set default value for `options`, the argument of `Mastodon`'s method `generateAuthUrl`?
I think it improves API consistency. (e.g. method `registerApp` has default value for the argument `options`)

**Comment by onsen-ui** [comment]
All authorization API's arguments `options` are changed to `Partial<object>` in recent minor update v0.1.1 :yum:

**Comment by aji-su** [comment]
I confirmed that it was improved! Thank you!
